#ifndef REALTIMEDATABASE_GLOBAL_H
#define REALTIMEDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REALTIMEDATABASE_LIBRARY)
#  define REALTIMEDATABASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REALTIMEDATABASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REALTIMEDATABASE_GLOBAL_H
