#ifndef STEREOCAMERA_GLOBAL_H
#define STEREOCAMERA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STEREOCAMERA_LIBRARY)
#  define STEREOCAMERASHARED_EXPORT Q_DECL_EXPORT
#else
#  define STEREOCAMERASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STEREOCAMERA_GLOBAL_H
