#ifndef RTDBSERVICE_GLOBAL_H
#define RTDBSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RTDBSERVICE_LIBRARY)
#  define RTDBSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTDBSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTDBSERVICE_GLOBAL_H
