#ifndef RTDBMANAGER_GLOBAL_H
#define RTDBMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RTDBMANAGER_LIBRARY)
#  define RTDBMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTDBMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTDBMANAGER_GLOBAL_H
